// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwgfMkR4dkBTV5j2ttI5-qwk8wb6jW6XY',
    appId: '1:212671425298:web:2c9c13084b3df4c67b61cb',
    messagingSenderId: '212671425298',
    projectId: 'smart-home-2bc83',
    authDomain: 'smart-home-2bc83.firebaseapp.com',
    databaseURL: 'https://smart-home-2bc83-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-2bc83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsydTwLfJ3ylM_yE1IAM91Wmph7X5IS0A',
    appId: '1:212671425298:android:88ffd4a2ff04d2c87b61cb',
    messagingSenderId: '212671425298',
    projectId: 'smart-home-2bc83',
    databaseURL: 'https://smart-home-2bc83-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-2bc83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKUfAzfLl7sKlNHYkv-hJXs3ErADB64z8',
    appId: '1:212671425298:ios:3059c98b2e44fce17b61cb',
    messagingSenderId: '212671425298',
    projectId: 'smart-home-2bc83',
    databaseURL: 'https://smart-home-2bc83-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-home-2bc83.appspot.com',
    iosBundleId: 'com.example.smartHomeControl',
  );
}
